angle_lim: 0.540
axis_distance: 0.105
baseline: 0.092
cog_distance: 0.0525
limit: 1.0
omega_max: 8.0
radius: 0.0318
trim: 0.0
v_max: 1.0

# Feed forward part
k_wheel: 14
# Feedback part: If velocity is measured, then the speed will be actively controlled
k_P: 1.0
k_I: 0.3